title: Mrunalini Dudhagawali
description: Personal website, life journal, and career projects.
baseurl: ""
url: "https://mrunalinidudhagawali8.github.io"

author:
  name: Mrunalini Dudhagawali
  email: your@email.com
  github: mrunalinidudhagawali8

plugins:
  - jekyll-feed
  - jekyll-seo-tag
