---
exclude: ['README.markdown']
permalink: ':title'
highlighter: pygments
safe: false

title: Mrunalini Dudhagawali
description: Backend Developer | Java | Spring Boot | AI Learner
baseurl: ""
url: "https://mrunalinidudhagawali8.github.io"

author:
  name: Mrunalini Dudhagawali
  email: dudhagawali@email.com
  github: https://github.com/mrunalinidudhagawali8/
  linkedin: https://www.linkedin.com/in/mrunalini-dudhagawali-35b46a128/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
